<?php    
class Webservices extends WireData implements Module {

	public static function getModuleInfo() {

		return array(
			'title' => 'Webservices', 
			'version' => 1, 
			'summary' => '',
			'singular' => true, 
			'autoload' => true, 
			'icon' => 'smile-o', 
			);
	}

	public function init() {
        $this->addHookBefore('Page::render', function () {
            
            if(isset($_GET['webservice']) ){
                $action = $_GET['action'];
                if($action == 'getFilteredActivities') {?>
                    <div>
                        <?php 
                            $pageid = $_GET['pageid'];
                            $page = $this->pages->get(intval($pageid));
                            foreach($page->activities() as $item) {?>
                                <li><?php echo date( "d. M-Y H:i", strtotime( $item->start_date_local ) ); ?>: 
                                    
                                    <a class="strava-link" target="_blank" href="https://www.strava.com/activities/<?php echo $item->id ?>"><?php echo $item->name ?></a> / 
                                    
                                    <a href="<?php echo $page->httpUrl; ?>?action=addEffort&activity=<?php echo $item->id; ?>">Registrer resultat</a></li>
                            <?php 
                            } ?>
                    </div>
                    <?php 
                }
                exit();
            }
            
            
        });
        
	}
}
?>

